# Generated by Django 6.1.1 on 2026-09-22 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_invoice_extra_amount_invoice_extra_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='battery_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='charger_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='chassis_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='extra_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='extra_notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='motor_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='spare_part',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='customer',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('hardware_details', models.TextField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing_app.invoice')),
            ],
        ),
    ]
